name: Test

on: [repository_dispatch]

jobs:
#  test:
#   runs-on: ubuntu-latest
#    strategy:
#      fail-fast: false
#    steps:
#      - uses: actions/checkout@v2
#      - name: Use Node.js 12.x
#        uses: actions/setup-node@v1
#        with:
#          node-version: 12.x
#      - run: npm install
#      - run: npm run build --if-present
#      - run: npm test
#        env:
#          CI: true
#      - name: Set up JDK 1.8
#        uses: actions/setup-java@v1
#        with:
#          java-version: 1.8
#      - name: Build release
#        run: npm run build:dist
#      - name: Run the tests in Docker
#        run: docker build . --file SMA/Dockerfile --build-arg image_tag=${{matrix.dockertag}} --tag magikcraft:${{matrix.dockertag}}
  report_success:
    runs-on: ubuntu-latest
 #   needs: test
    steps:
      - name: Tell Camunda Cloud What's up!
        uses: jwulf/zeebe-action@0.2.0
        with:
          zeebe_address: ${{ secrets.ZEEBE_ADDRESS }}
          zeebe_client_id: ${{ secrets.ZEEBE_CLIENT_ID }}
          zeebe_authorization_server_url: ${{ secrets.ZEEBE_AUTHORIZATION_SERVER_URL }}
          zeebe_client_secret: ${{ secrets.ZEEBE_CLIENT_SECRET }}
          operation: publishMessage
          message_name: PLUGINS_GREEN
          correlationKey: ${{ github.event.client_payload.buildid }}
